### ISSUE TITLE
Add custom title to video and genre

### ISSUE THREAD

**Issue by condef5** [condef5/animeplayer#2]
You could add a modal and a floating style bottom, it's just a suggestion

**Comment by mohinderps** [comment]
Can you explain it in more detail.

**Comment by condef5** [comment]
A floating button, that opens a popup window and there paste the url of the video (and be able to add a title and genre to the video)
![button](https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1MASERR7SyFbkPDYK6WsimAEx1SzL9hq4%2Ffab-layout-container-do.png)

**Comment by sasalx** [comment]
I can take it.

**Comment by condef5** [comment]
Cool :)
